from typing import Protocol, List, Optional
from src.knowledge_base_backend.domain.entities.instrument import Instrument

class InstrumentRepository(Protocol):
    async def get_by_id(self, id: int) -> Optional[Instrument]: ...
    async def get_by_name(self, name: str) -> Optional[Instrument]: ...
    async def get_all(self) -> List[Instrument]: ...
