from typing import Protocol, List
from src.knowledge_base_backend.domain.entities.instrument_memory_entry import InstrumentMemoryEntry


class InstrumentMemoryRepository(Protocol):
    async def save_memory_entry(self, entry: InstrumentMemoryEntry) -> InstrumentMemoryEntry: ...
    async def get_memory_for_instrument(self, instrument_id: int, limit: int = 20) -> List[InstrumentMemoryEntry]: ...
    async def get_all_latest_entries(self) -> List[InstrumentMemoryEntry]: ...
