from typing import Protocol, List
from src.knowledge_base_backend.domain.value_objects.text_embedding import TextEmbedding

class EmbeddingGenerationService(Protocol):
    async def generate_text_embedding(self, text: str) -> TextEmbedding: ...
    async def generate_multiple_text_embeddings(self, texts: List[str]) -> List[TextEmbedding]: ...
    def retrieve_embedding_dimension(self) -> int: ...
    def retrieve_model_identifier(self) -> str: ...
