from typing import Protocol, List, Optional
from src.knowledge_base_backend.domain.entities.knowledge_base_article import KnowledgeBaseArticle
from src.knowledge_base_backend.domain.value_objects.article_search_criteria import ArticleSearchCriteria
from src.knowledge_base_backend.domain.value_objects.pagination_request import PaginationRequest
from src.knowledge_base_backend.domain.value_objects.pagination_result import PaginationResult

class ArticleRepository(Protocol):
    async def retrieve_paginated_articles(
        self, criteria: ArticleSearchCriteria, pagination: PaginationRequest
    ) -> PaginationResult[KnowledgeBaseArticle]: ...
    
    async def count_articles_matching_criteria(self, criteria: ArticleSearchCriteria) -> int: ...
    
    async def retrieve_article_by_number(self, article_number: str) -> Optional[KnowledgeBaseArticle]: ...
    
    async def retrieve_article_by_database_id(self, database_id: int) -> Optional[KnowledgeBaseArticle]: ...
    
    async def retrieve_articles_by_identifiers(self, database_ids: List[int]) -> List[KnowledgeBaseArticle]: ...
    
    async def search_articles_by_full_text(self, criteria: ArticleSearchCriteria, limit: int) -> List[KnowledgeBaseArticle]: ...

    async def count_all_articles(self) -> int: ...
