from typing import Protocol
from src.knowledge_base_backend.domain.entities.monitoring_issue import MonitoringIssue

class MonitoringRepository(Protocol):
    async def save_issue(self, issue: MonitoringIssue) -> MonitoringIssue: ...
    async def get_active_logs_count(self) -> int: ...
    async def get_detected_issues_count(self) -> int: ...
