from typing import Protocol, Optional
from src.knowledge_base_backend.domain.entities.user_account import UserAccount

class UserRepository(Protocol):
    async def get_by_username(self, username: str) -> Optional[UserAccount]: ...
    async def get_by_id(self, id: int) -> Optional[UserAccount]: ...
    async def save(self, user: UserAccount) -> UserAccount: ...
