from typing import Protocol, Optional, Dict, Any

class AuthenticationTokenService(Protocol):
    def create_access_token(self, subject: str) -> str: ...
    def validate_access_token(self, token: str) -> str: ...
    def create_password_reset_token(
        self, subject: str, token_hash_salt: Optional[str] = None, expires_delta_minutes: Optional[int] = None
    ) -> str: ...
    def validate_password_reset_token(self, token: str) -> Dict[str, Any]: ...
