from typing import Protocol, BinaryIO

class PersistentFileStorage(Protocol):
    async def store_persistent_file(self, instrument_id: int, filename: str, file_stream: BinaryIO) -> str: ...
    async def get_file_path(self, instrument_id: int, filename: str) -> str: ...
